name: build

on:
  push:
    branches: [main, dev]
  release:
    types: [created]

jobs:
  build_docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: devcontainer
          imageTag: stash
          runCmd: "true"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            "IMAGE=devcontainer:stash"
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devcontainer-python:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/devcontainer-python:latest
